<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Terms and Conditions</title>
<link href="css/style.css" rel="stylesheet" type="text/css" media="all"/>
</head>

<body>
<?php include ("inc/header.php");?>
<div class="terms">
<h1>Oregon Green Host LLC Website Hosting Terms and Conditions</h1>  
<p><strong>Revision Date: April 23, 2015</strong></p>
<br />
<p>This Hosting Agreement governs your purchase and use, in any manner, of all Web site hosting, ordered by you and accepted by Oregon Green Host LLC and describes the terms and conditions that apply to such purchase and use of the Services. You AGREE TO BE BOUND BY THE TERMS AND CONDITIONS CONTAINED HEREIN. Oregon Green Host LLC reserves the right to change or modify any of the terms and conditions contained in this Agreement at any time and from time to time in its sole discretion, and to determine whether and when any such changes apply to both existing or future customers. Oregon Green Host LLC may make changes or modifications to referenced policies and guidelines without notice to you. Your continued use of the Services following Oregon Green Host LLC' posting of any changes or modifications will constitute your acceptance of such changes or modifications.</p>  
<br />
<p>1. Payment. As consideration for Oregon Green Host LLC providing the Hosting Services hereunder, Customer agrees to pay Oregon Green Host LLC the aggregate monthly fee based on the monthly hosting services and the terms selected.</p> 
<br />
<p>2. Provision of Services. Oregon Green Host LLC will provide Customer with the Services ordered that are described in the Hosting Package Features elsewhere in this document. Customer understands and agrees that Oregon Green Host LLC will host and create the Web site solely in accordance with the information provided by Customer.</p>  
<br />
<p>3. Rights to the Web Site and Content. With the exception of any Third-Party Materials and Background Technology as set forth in Section 4, Customer owns the Customer Content. "Customer Content" means all content or information (including, without limitation, any text, music, sound, photographs, video, graphics, data, or software), in any medium, provided by Customer to Oregon Green Host LLC. "Third-Party Materials" means any content, software, or other computer programming material that is owned by an entity other than Oregon Green Host LLC, and licensed by Oregon Green Host LLC or generally available to the public, including Customer, under published licensing terms, and that Oregon Green Host LLC will use to display or run a Web site. Oregon Green Host LLC owns the rights to the design of the web site. If a customer stops paying the monthly fee for the web site upon cancellation the customer is not entitled to use the web site for any purposes whatsoever.</p>  
<br />
<p>4. Limited License to the Background Technology. "Background Technology" means computer programming/formatting code or operating instructions developed by or for Oregon Green Host LLC and used to host or operate the Web site or a Web server in connection with a Web site. Background Technology includes, but is not limited to, any files necessary to make forms, buttons, checkboxes, and similar functions and underlying technology or components, such as style sheets, animation templates, interface programs that link multimedia and other programs, customized graphics manipulation engines, and menu utilities, whether in database form or dynamically driven. Background Technology does not include any Customer Content. Customer may not duplicate or distribute any Background Technology to any third party without the prior written consent of Oregon Green Host LLC. All rights to the Background Technology not expressly granted to Customer hereunder are retained by Oregon Green Host LLC. Without limiting the foregoing, Customer agrees not to reverse-engineer, reverse-assemble, decompile, or otherwise attempt to derive any source code of the Background Technology, except as allowed by law.</p>  
<br />
<p>5. Limited License to Content. Customer hereby grants to Oregon Green Host LLC the limited, nonexclusive right and license to copy, distribute, transmit, display, perform, create derivative works from, modify, and otherwise use and exploit Web site, any Customer Content, or any Customer Marks provided to Oregon Green Host LLC hereunder, solely for the purpose of rendering Oregon Green Host LLC' Services under this Agreement. Such limited right and license shall extend to no other materials or for any other purpose and will terminate automatically upon termination of this Agreement for any reason. </p> 
<br />
<p>6. Content Standards. Customer agrees not to provide Customer Content, and Oregon Green Host LLC will not intentionally provide to Customers any content, that (a) infringes on any third party's intellectual property or publicity/privacy rights; (b) violates any applicable law or regulation; (c) is defamatory, violent, clearly harmful, or obscene or pornographic or infringes on citizens' rights; or (d) contains any viruses, Trojan horses, worms, time bombs, cancel bots, or other computer programming routines that are intended to damage or interfere with any system, data, or personal information. If Customer is international, then Customer agrees to comply with all applicable local and national laws. Oregon Green Host LLC reserves the right to refuse any other subject matter it deems inappropriate.</p><br />
<p>7. Support. Oregon Green Host LLC agrees to provide reasonable technical support by email to Customer during Oregon Green Host LLC's normal technical support hours. Oregon Green Host LLC will provide customer support by telephone if the customer purchased telephonic support time.</p>  
<br />
<p>8. Term and Termination. (a) This Agreement is effective as of the Effective Date and shall continue unless terminated; (b) Oregon Green Host LLC may terminate this Agreement after five (5) days' written notice to Customer if Customer materially breaches this Agreement, including, without limitation, failure to pay, and fails to cure such breach during such five (5) day period; and (c) upon the termination of this Agreement, Customer will pay Oregon Green Host LLC for all Services provided to Customer by Oregon Green Host LLC prior to termination. Sections 2, 3, 4, 5, 9, 11, and 12 will survive termination of this Agreement.</p>  
<br />
<p>9. Warranty Disclaimer. Except as expressly provided in this Agreement, the Services are provided "as is," and Oregon Green Host LLC expressly disclaims all warranties and conditions of any kind, express, implied, or statutory, including, without limitation, the implied warranties of title, non-infringement, merchantability, and fitness for a particular purpose. Interruption of Service: You hereby acknowledge and agree that Oregon Green Host LLC will not be liable for any temporary delay, outages or interruptions of the Services. Each party acknowledges that it has not entered into this Agreement in reliance upon any warranty or representation except those specifically set forth herein. Unless an approval process is specified herein or in a Statement, all Hosting provided by Oregon Green Host LLC to a Customer will be deemed accepted when delivered.</p>  
<br />
<p>10. Indemnity. (a) Customer Indemnity. Customer will defend Oregon Green Host LLC against any third-party claim, action, suit, or proceeding alleging any breach of the covenants contained in Section . Subject to Section 11, Customer shall indemnify Oregon Green Host LLC for all losses, damages, liabilities, and all reasonable expenses and costs incurred by Oregon Green Host LLC as a result of any such third-party claim, action, suit, or proceeding. (b) Oregon Green Host LLC' Indemnity. Oregon Green Host LLC will defend Customer against any third-party claim, action, suit, or proceeding alleging any breach of the covenants contained in Section 6. Subject to Section 11, Oregon Green Host LLC shall indemnify Customer for all losses, damages, liabilities, and all reasonable expenses and costs incurred by Customer as a result of any such third party claim, action, suit, or proceeding. (c) Mechanics of Indemnity. The indemnifying party's obligations are conditioned upon the indemnified party: (i) giving the indemnifying party prompt, written notice of any claim, action, suit, or proceeding for which the indemnified party is seeking indemnity; (ii) granting control of the defense and settlement to the indemnifying party; and (iii) reasonably cooperating with the indemnifying party at the indemnifying party's expense.</p> 
<br />
<p>11. Limitation of Liability. Oregon Green Host LLC's LIABILITY HEREUNDER SHALL NOT EXCEED THE AMOUNT PAID BY CUSTOMER TO Oregon Green Host LLC DURING THE THREE (3) MONTH PERIOD BEFORE THE ACTION AROSE. Oregon Green Host LLC SHALL NOT BE LIABLE FOR (A) ANY LOSS OF USE, LOSS OF DATA, OR INTERRUPTION OF BUSINESS OR (B) ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES OF ANY KIND (INCLUDING, WITHOUT LIMITATION, LOST PROFITS), REGARDLESS OF THE FORM OR ACTION, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR OTHERWISE, EVEN IF Oregon Green Host LLC HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. CUSTOMER ACKNOWLEDGES THAT THESE LIMITATIONS ARE AN ESSENTIAL ELEMENT OF THIS AGREEMENT, AND ABSENT SUCH LIMITATIONS, Oregon Green Host LLC WOULD NOT ENTER INTO THIS AGREEMENT.</p> 
<br />
</div>
 <?php include ("inc/footer.php");?>
</body>
</html>
